# Generates lib/development_web/live/showcase/preview_generated.ex
#
# One `show/1` clause per component, driven by the live catalog + light source
# introspection of each generated component. The component NAME must be static in
# HEEx, so we emit a clause per component; everything else (the chosen props) is
# spread generically via `{@props}`.
#
#   Run:  mix run gen_showcase.exs
#
# Re-run whenever components are (re)generated. Curated, richer previews for
# composite components live as hand-written overrides in `preview.ex`, which falls
# back to this generated module.

alias DevelopmentWeb.Showcase.Catalog

out = "lib/development_web/live/showcase/preview_generated.ex"
components = Catalog.all()

# The catalog file name is not always the public function name
# (e.g. input_field -> input, layout -> flex, typography -> p). The generated
# aggregator `mishka_components.ex` lists the real arity-1 functions per module,
# so use it as the source of truth and pick a primary function per component.
# Components with a hand-written, richer clause in `preview.ex` — skip them here so we
# don't emit a shadowed generic clause (which would warn about missing required slots).
overridden =
  ~w(accordion carousel tabs checkbox_card radio_card clipboard image video pagination
     form_wrapper email_field collapse dock)

aggregator = File.read!("lib/development_web/components/mishka_components.ex")

module_funs =
  ~r/import DevelopmentWeb\.Components\.(\w+),\s*only:\s*\[([^\]]*)\]/
  |> Regex.scan(aggregator)
  |> Map.new(fn [_, mod, only] ->
    funs = Regex.scan(~r/(\w+):\s*1\b/, only) |> Enum.map(fn [_, f] -> f end)
    {mod, funs}
  end)

primary_fun = fn name ->
  funs = Map.get(module_funs, Macro.camelize(name), [])

  cond do
    name in funs -> name
    funs != [] -> hd(funs)
    true -> name
  end
end

strategy = fn %{name: name} ->
  src_path = "lib/development_web/components/#{name}.ex"

  case File.read(src_path) do
    {:ok, src} ->
      cond do
        name == "icon" -> :icon
        Regex.match?(~r/attr :field,\s*Phoenix\.HTML\.FormField/, src) -> :field
        String.contains?(src, "slot :inner_block") -> :inner
        true -> :void
      end

    _ ->
      :void
  end
end

# Text-like field components that benefit from a realistic placeholder in the preview. (Fields like
# checkbox/radio/toggle/color/range/date don't take a text placeholder, so they're omitted.)
placeholders = %{
  "search_field" => "Search...",
  "url_field" => "https://example.com",
  "tel_field" => "+1 (555) 000-0000",
  "password_field" => "Enter your password",
  "number_field" => "Enter a number",
  "text_field" => "Type something...",
  "textarea_field" => "Write your message..."
}

clause = fn comp ->
  name = comp.name
  fun = primary_fun.(name)

  # `id={@id}` is harmless for components that don't declare an `:id` attr (it lands
  # in their `:global` rest) and satisfies the many that require one.
  body =
    case strategy.(comp) do
      :icon ->
        ~s|    <.#{fun} id={@id} name="hero-sparkles" {@props} />|

      :field ->
        ph =
          case placeholders[name] do
            nil -> ""
            text -> ~s| placeholder="#{text}"|
          end

        ~s|    <.#{fun} id={@id} field={@form[:demo]} label="Demo field"#{ph} {@props} />|

      :inner ->
        ~s|    <.#{fun} id={@id} {@props}>{@sample}</.#{fun}>|

      :void ->
        ~s|    <.#{fun} id={@id} {@props} />|
    end

  """
    def show(%{component: #{inspect(name)}} = assigns) do
      ~H\"\"\"
  #{body}
      \"\"\"
    end
  """
end

emitted = Enum.reject(components, &(&1.name in overridden))
clauses = Enum.map_join(emitted, "\n", clause)

contents = """
# AUTO-GENERATED by gen_showcase.exs — do not edit by hand.
# Re-run: mix run gen_showcase.exs
defmodule DevelopmentWeb.Showcase.PreviewGenerated do
  @moduledoc false
  use DevelopmentWeb, :html

#{clauses}
  def show(assigns) do
    ~H\"\"\"
    <p class="text-sm text-base-content/60">
      No generated preview for <code>{@component}</code>.
    </p>
    \"\"\"
  end
end
"""

File.write!(out, contents)

counts =
  emitted
  |> Enum.group_by(strategy)
  |> Enum.map(fn {k, v} -> "#{k}: #{length(v)}" end)
  |> Enum.join(", ")

IO.puts(
  "Wrote #{out} with #{length(emitted)} generated clauses " <>
    "(#{counts}); #{length(overridden)} overridden in preview.ex"
)
