# AUTO-GENERATED by gen_showcase.exs — do not edit by hand.
# Re-run: mix run gen_showcase.exs
defmodule DevelopmentWeb.Showcase.PreviewGenerated do
  @moduledoc false
  use DevelopmentWeb, :html

  def show(%{component: "alert"} = assigns) do
    ~H"""
    <.alert id={@id} {@props}>{@sample}</.alert>
    """
  end

  def show(%{component: "avatar"} = assigns) do
    ~H"""
    <.avatar id={@id} {@props}>{@sample}</.avatar>
    """
  end

  def show(%{component: "badge"} = assigns) do
    ~H"""
    <.badge id={@id} {@props}>{@sample}</.badge>
    """
  end

  def show(%{component: "banner"} = assigns) do
    ~H"""
    <.banner id={@id} {@props}>{@sample}</.banner>
    """
  end

  def show(%{component: "blockquote"} = assigns) do
    ~H"""
    <.blockquote id={@id} {@props}>{@sample}</.blockquote>
    """
  end

  def show(%{component: "breadcrumb"} = assigns) do
    ~H"""
    <.breadcrumb id={@id} {@props}>{@sample}</.breadcrumb>
    """
  end

  def show(%{component: "button"} = assigns) do
    ~H"""
    <.button id={@id} {@props}>{@sample}</.button>
    """
  end

  def show(%{component: "card"} = assigns) do
    ~H"""
    <.card id={@id} {@props}>{@sample}</.card>
    """
  end

  def show(%{component: "chat"} = assigns) do
    ~H"""
    <.chat id={@id} {@props}>{@sample}</.chat>
    """
  end

  def show(%{component: "checkbox_field"} = assigns) do
    ~H"""
    <.checkbox_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "color_field"} = assigns) do
    ~H"""
    <.color_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "combobox"} = assigns) do
    ~H"""
    <.combobox id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "date_time_field"} = assigns) do
    ~H"""
    <.date_time_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "device_mockup"} = assigns) do
    ~H"""
    <.device_mockup id={@id} {@props}>{@sample}</.device_mockup>
    """
  end

  def show(%{component: "divider"} = assigns) do
    ~H"""
    <.divider id={@id} {@props} />
    """
  end

  def show(%{component: "drawer"} = assigns) do
    ~H"""
    <.drawer id={@id} {@props}>{@sample}</.drawer>
    """
  end

  def show(%{component: "dropdown"} = assigns) do
    ~H"""
    <.dropdown id={@id} {@props}>{@sample}</.dropdown>
    """
  end

  def show(%{component: "fieldset"} = assigns) do
    ~H"""
    <.fieldset id={@id} {@props}>{@sample}</.fieldset>
    """
  end

  def show(%{component: "file_field"} = assigns) do
    ~H"""
    <.file_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "footer"} = assigns) do
    ~H"""
    <.footer id={@id} {@props}>{@sample}</.footer>
    """
  end

  def show(%{component: "gallery"} = assigns) do
    ~H"""
    <.gallery id={@id} {@props}>{@sample}</.gallery>
    """
  end

  def show(%{component: "icon"} = assigns) do
    ~H"""
    <.icon id={@id} name="hero-sparkles" {@props} />
    """
  end

  def show(%{component: "indicator"} = assigns) do
    ~H"""
    <.indicator id={@id} {@props} />
    """
  end

  def show(%{component: "input_field"} = assigns) do
    ~H"""
    <.input id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "jumbotron"} = assigns) do
    ~H"""
    <.jumbotron id={@id} {@props}>{@sample}</.jumbotron>
    """
  end

  def show(%{component: "keyboard"} = assigns) do
    ~H"""
    <.keyboard id={@id} {@props}>{@sample}</.keyboard>
    """
  end

  def show(%{component: "layout"} = assigns) do
    ~H"""
    <.flex id={@id} {@props}>{@sample}</.flex>
    """
  end

  def show(%{component: "list"} = assigns) do
    ~H"""
    <.list id={@id} {@props}>{@sample}</.list>
    """
  end

  def show(%{component: "mega_menu"} = assigns) do
    ~H"""
    <.mega_menu id={@id} {@props}>{@sample}</.mega_menu>
    """
  end

  def show(%{component: "menu"} = assigns) do
    ~H"""
    <.menu id={@id} {@props}>{@sample}</.menu>
    """
  end

  def show(%{component: "modal"} = assigns) do
    ~H"""
    <.modal id={@id} {@props}>{@sample}</.modal>
    """
  end

  def show(%{component: "native_select"} = assigns) do
    ~H"""
    <.native_select id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "navbar"} = assigns) do
    ~H"""
    <.navbar id={@id} {@props}>{@sample}</.navbar>
    """
  end

  def show(%{component: "number_field"} = assigns) do
    ~H"""
    <.number_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="Enter a number"
      {@props}
    />
    """
  end

  def show(%{component: "overlay"} = assigns) do
    ~H"""
    <.overlay id={@id} {@props}>{@sample}</.overlay>
    """
  end

  def show(%{component: "password_field"} = assigns) do
    ~H"""
    <.password_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="Enter your password"
      {@props}
    />
    """
  end

  def show(%{component: "popover"} = assigns) do
    ~H"""
    <.popover id={@id} {@props}>{@sample}</.popover>
    """
  end

  def show(%{component: "progress"} = assigns) do
    ~H"""
    <.progress id={@id} {@props}>{@sample}</.progress>
    """
  end

  def show(%{component: "radio_field"} = assigns) do
    ~H"""
    <.radio_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "range_field"} = assigns) do
    ~H"""
    <.range_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "rating"} = assigns) do
    ~H"""
    <.rating id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "scroll_area"} = assigns) do
    ~H"""
    <.scroll_area id={@id} {@props}>{@sample}</.scroll_area>
    """
  end

  def show(%{component: "search_field"} = assigns) do
    ~H"""
    <.search_field id={@id} field={@form[:demo]} label="Demo field" placeholder="Search..." {@props} />
    """
  end

  def show(%{component: "shape"} = assigns) do
    ~H"""
    <.shape id={@id} {@props}>{@sample}</.shape>
    """
  end

  def show(%{component: "sidebar"} = assigns) do
    ~H"""
    <.sidebar id={@id} {@props}>{@sample}</.sidebar>
    """
  end

  def show(%{component: "skeleton"} = assigns) do
    ~H"""
    <.skeleton id={@id} {@props} />
    """
  end

  def show(%{component: "speed_dial"} = assigns) do
    ~H"""
    <.speed_dial id={@id} {@props}>{@sample}</.speed_dial>
    """
  end

  def show(%{component: "spinner"} = assigns) do
    ~H"""
    <.spinner id={@id} {@props} />
    """
  end

  def show(%{component: "stat"} = assigns) do
    ~H"""
    <.stat id={@id} {@props}>{@sample}</.stat>
    """
  end

  def show(%{component: "stepper"} = assigns) do
    ~H"""
    <.stepper id={@id} {@props}>{@sample}</.stepper>
    """
  end

  def show(%{component: "table"} = assigns) do
    ~H"""
    <.table id={@id} {@props}>{@sample}</.table>
    """
  end

  def show(%{component: "table_content"} = assigns) do
    ~H"""
    <.table_content id={@id} {@props}>{@sample}</.table_content>
    """
  end

  def show(%{component: "tel_field"} = assigns) do
    ~H"""
    <.tel_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="+1 (555) 000-0000"
      {@props}
    />
    """
  end

  def show(%{component: "text_field"} = assigns) do
    ~H"""
    <.text_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="Type something..."
      {@props}
    />
    """
  end

  def show(%{component: "textarea_field"} = assigns) do
    ~H"""
    <.textarea_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="Write your message..."
      {@props}
    />
    """
  end

  def show(%{component: "timeline"} = assigns) do
    ~H"""
    <.timeline id={@id} {@props}>{@sample}</.timeline>
    """
  end

  def show(%{component: "toast"} = assigns) do
    ~H"""
    <.toast id={@id} {@props}>{@sample}</.toast>
    """
  end

  def show(%{component: "toggle_field"} = assigns) do
    ~H"""
    <.toggle_field id={@id} field={@form[:demo]} label="Demo field" {@props} />
    """
  end

  def show(%{component: "tooltip"} = assigns) do
    ~H"""
    <.tooltip id={@id} {@props}>{@sample}</.tooltip>
    """
  end

  def show(%{component: "typography"} = assigns) do
    ~H"""
    <.h1 id={@id} {@props}>{@sample}</.h1>
    """
  end

  def show(%{component: "url_field"} = assigns) do
    ~H"""
    <.url_field
      id={@id}
      field={@form[:demo]}
      label="Demo field"
      placeholder="https://example.com"
      {@props}
    />
    """
  end

  def show(assigns) do
    ~H"""
    <p class="text-sm text-base-content/60">
      No generated preview for <code>{@component}</code>.
    </p>
    """
  end
end
