// beam_jni.c — JNI entry points for MishkaMob.
// Generated by mix mob.new. Edit the two defines below; do not touch the rest.

#include <jni.h>
#include "mob_beam.h"

#define BRIDGE_CLASS  "com/example/mishka_mob/MobBridge"
#define APP_MODULE    "mishka_mob"

JavaVM* g_jvm      = NULL;
jobject g_activity = NULL;

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    JNIEnv* env;
    (*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6);
    mob_ui_cache_class(env, BRIDGE_CLASS);
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MainActivity_nativeSetActivity(JNIEnv* env, jobject thiz, jobject activity) {
    mob_init_bridge(env, activity);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MainActivity_nativeStartBeam(JNIEnv* env, jobject thiz) {
    mob_start_beam(APP_MODULE);
}

// Called from MainActivity.onConfigurationChanged on a rotation. Forwards the
// new orientation string to the BEAM. mob_send_orientation_changed is exported
// by mob_nif.zig; declared here in case it's not in mob_beam.h.
extern void mob_send_orientation_changed(const char* orient);

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MainActivity_nativeNotifyOrientation(JNIEnv* env, jobject thiz, jstring orient) {
    const char* utf8 = (*env)->GetStringUTFChars(env, orient, NULL);
    mob_send_orientation_changed(utf8);
    (*env)->ReleaseStringUTFChars(env, orient, utf8);
}

// Called from MainActivity's ConnectivityManager.NetworkCallback when the active
// network path changes. Forwards online/transport/expensive to the BEAM
// (Mob.Device.network_state/0 + :network subscribers).
// mob_send_connectivity_changed is exported by mob_nif.zig.
extern void mob_send_connectivity_changed(int online, const char* transport, int expensive,
    int validated);

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MainActivity_nativeNotifyConnectivity(JNIEnv* env, jobject thiz,
    jboolean online, jstring transport, jboolean expensive, jboolean validated) {
    // utf8 is NULL if transport is null OR GetStringUTFChars failed (OOM); pass
    // "none" in that case and only release what we actually acquired.
    const char* utf8 = transport ? (*env)->GetStringUTFChars(env, transport, NULL) : NULL;
    mob_send_connectivity_changed(online ? 1 : 0, utf8 ? utf8 : "none", expensive ? 1 : 0,
        validated ? 1 : 0);
    if (utf8) (*env)->ReleaseStringUTFChars(env, transport, utf8);
}

// Called from MobBridge.nativeSendTap(handle) in Kotlin when a button is tapped.
JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_tap((int)handle);
}

// Called from MobBridge.nativeSendChangeStr/Bool/Float when an input widget changes.
JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendChangeStr(JNIEnv* env, jclass cls, jint handle, jstring value) {
    const char* utf8 = (*env)->GetStringUTFChars(env, value, NULL);
    mob_send_change_str((int)handle, utf8);
    (*env)->ReleaseStringUTFChars(env, value, utf8);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendChangeBool(JNIEnv* env, jclass cls, jint handle, jboolean value) {
    mob_send_change_bool((int)handle, (int)value);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendChangeFloat(JNIEnv* env, jclass cls, jint handle, jfloat value) {
    mob_send_change_float((int)handle, (double)value);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendFocus(JNIEnv* env, jclass cls, jint handle) {
    mob_send_focus((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendBlur(JNIEnv* env, jclass cls, jint handle) {
    mob_send_blur((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSendSubmit(JNIEnv* env, jclass cls, jint handle) {
    mob_send_submit((int)handle);
}

// Called from MobBridge.nativeHandleBack() when the Android back gesture fires.
JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeHandleBack(JNIEnv* env, jclass cls) {
    mob_handle_back();
}

// Called from MobBridge.notifyColorSchemeChanged when MainActivity's
// onConfigurationChanged sees a uiMode flip. `scheme` is "light" or "dark".
JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeNotifyColorScheme(JNIEnv* env, jclass cls,
    jstring scheme) {
    if (!scheme) return;
    const char* utf8 = (*env)->GetStringUTFChars(env, scheme, NULL);
    if (utf8) {
        mob_send_color_scheme_changed(utf8);
        (*env)->ReleaseStringUTFChars(env, scheme, utf8);
    }
}

// ── Device capability result delivery ────────────────────────────────────
// Called from MobBridge when async results are ready.

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverAtom2(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    mob_deliver_atom2(pid, ca1, ca2);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverAtom3(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2, jstring a3) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    const char* ca3 = (*env)->GetStringUTFChars(env, a3, NULL);
    mob_deliver_atom3(pid, ca1, ca2, ca3);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
    (*env)->ReleaseStringUTFChars(env, a3, ca3);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverMotion(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz, jlong ts) {
    mob_deliver_motion(pid, ax, ay, az, gx, gy, gz, (long long)ts);
}

// mob_deliver_motion_mag is exported by mob_nif.zig; declared here in case the
// installed mob_beam.h predates the magnetometer/heading delivery function.
extern void mob_deliver_motion_mag(jlong pid, double ax, double ay, double az,
                                   double gx, double gy, double gz, double mx,
                                   double my, double mz, double heading,
                                   long long ts);

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverMotionMag(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz,
    jdouble mx, jdouble my, jdouble mz, jdouble heading, jlong ts) {
    mob_deliver_motion_mag(pid, ax, ay, az, gx, gy, gz, mx, my, mz, heading,
                           (long long)ts);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverFileResult(JNIEnv* env, jclass cls,
    jlong pid, jstring event, jstring sub, jstring json_items) {
    const char* ce  = (*env)->GetStringUTFChars(env, event, NULL);
    const char* cs  = (*env)->GetStringUTFChars(env, sub,   NULL);
    const char* cj  = json_items ? (*env)->GetStringUTFChars(env, json_items, NULL) : NULL;
    mob_deliver_file_result(pid, ce, cs, cj);
    (*env)->ReleaseStringUTFChars(env, event, ce);
    (*env)->ReleaseStringUTFChars(env, sub,   cs);
    if (cj) (*env)->ReleaseStringUTFChars(env, json_items, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverPushToken(JNIEnv* env, jclass cls,
    jlong pid, jstring token) {
    const char* ct = (*env)->GetStringUTFChars(env, token, NULL);
    mob_deliver_push_token(pid, ct);
    (*env)->ReleaseStringUTFChars(env, token, ct);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverNotification(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_notification(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeSetLaunchNotification(JNIEnv* env, jclass cls,
    jstring json) {
    if (!json) { mob_set_launch_notification(NULL); return; }
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_set_launch_notification(cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverWebViewMessage(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_webview_message(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverWebViewBlocked(JNIEnv* env, jclass cls,
    jlong pid, jstring url) {
    const char* cu = (*env)->GetStringUTFChars(env, url, NULL);
    mob_deliver_webview_blocked(pid, cu);
    (*env)->ReleaseStringUTFChars(env, url, cu);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverAlertAction(JNIEnv* env, jclass cls,
    jstring action) {
    const char* ca = (*env)->GetStringUTFChars(env, action, NULL);
    mob_deliver_alert_action(ca);
    (*env)->ReleaseStringUTFChars(env, action, ca);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverComponentEvent(JNIEnv* env, jclass cls,
    jint handle, jstring event, jstring payload_json) {
    const char* ce = (*env)->GetStringUTFChars(env, event,        NULL);
    const char* cj = (*env)->GetStringUTFChars(env, payload_json, NULL);
    mob_send_component_event((int)handle, ce, cj);
    (*env)->ReleaseStringUTFChars(env, event,        ce);
    (*env)->ReleaseStringUTFChars(env, payload_json, cj);
}

// ── Mob.Peripheral.VendorUsb delivery thunks ─────────────────────────────────
// Called from MobBridge's USB code when Android USB host events fire.
// See lib/mob/peripheral/vendor_usb.ex for the public message envelope shape.

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbDevices(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_vendor_usb_devices(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbPermission(JNIEnv* env, jclass cls,
    jlong pid, jboolean granted, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_permission(pid, granted ? 1 : 0, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbOpened(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_opened(pid, (int)session_id, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbData(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jbyteArray bytes, jint len) {
    if (!bytes || len <= 0) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, NULL, 0);
        return;
    }
    jbyte* buf = (*env)->GetByteArrayElements(env, bytes, NULL);
    if (buf) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, (const uint8_t*)buf, (size_t)len);
        (*env)->ReleaseByteArrayElements(env, bytes, buf, JNI_ABORT);
    }
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbWriteComplete(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jint bytes_written) {
    mob_deliver_vendor_usb_write_complete(pid, (int)session_id, (int)bytes_written);
}

JNIEXPORT void JNICALL
Java_com_example_mishka_1mob_MobBridge_nativeDeliverVendorUsbEvent(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring tag, jstring reason) {
    const char* ct = (*env)->GetStringUTFChars(env, tag, NULL);
    const char* cr = reason ? (*env)->GetStringUTFChars(env, reason, NULL) : NULL;
    mob_deliver_vendor_usb_event(pid, (int)session_id, ct, cr);
    (*env)->ReleaseStringUTFChars(env, tag, ct);
    if (cr) (*env)->ReleaseStringUTFChars(env, reason, cr);
}
