defmodule Mix.Tasks.Mishka.Ui.Gen.Mob.Components do
  use Igniter.Mix.Task

  alias MishkaChelekom.Generators.Core
  alias MishkaChelekom.Generators.Mob.{Locations, Registry}

  @example "mix mishka.ui.gen.mob.components drawer,dialog,tabs"
  @shortdoc "Generate several (or all) native Mob components at once"
  @moduledoc """
  #{@shortdoc}

  Names are comma-separated, or pass `--all` for every component in `priv/mob`.

  Each component is generated by `mix mishka.ui.gen.mob`, so dependencies and the
  shared kit are handled exactly as they are for a single one. The composite
  registry is written **once at the end** rather than after each component —
  rebuilding it 72 times would be correct but pointlessly slow.

  ## Example

  ```bash
  #{@example}
  mix mishka.ui.gen.mob.components --all --exclude editor
  ```

  ## Options

  * `--all` - Every component in the catalog
  * `--exclude` - Comma-separated names to skip
  * `--component-prefix` - Prefix for public function names
  * `--module-prefix` - Prefix for module names
  * `--no-save` - Use prefixes without saving them to config
  * `--no-register` - Do not write the composite-tag registry
  * `--yes` - Apply without prompts
  """

  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      example: @example,
      positional: [{:components, optional: true}],
      group: :mishka_chelekom,
      schema: [
        all: :boolean,
        exclude: :string,
        component_prefix: :string,
        module_prefix: :string,
        no_save: :boolean,
        no_register: :boolean
      ]
    }
  end

  def supports_umbrella?(), do: false

  def igniter(igniter) do
    igniter
    |> Registry.check_dependency()
    |> Locations.assign_namespace()
    |> assign_requested()
    |> generate_each()
    |> write_registry()
  end

  defp assign_requested(igniter) do
    %Igniter.Mix.Task.Args{positional: positional, options: options} = igniter.args
    available = Core.all_component_names(igniter, :mob)
    excluded = split(options[:exclude])

    requested =
      cond do
        options[:all] -> available
        is_binary(positional[:components]) -> split(positional[:components])
        true -> []
      end

    unknown = requested -- available

    cond do
      requested == [] ->
        Igniter.add_issue(
          igniter,
          "Name at least one component, or pass --all. Available: #{Enum.join(available, ", ")}"
        )

      unknown != [] ->
        Igniter.add_issue(igniter, "Unknown Mob component(s): #{Enum.join(unknown, ", ")}")

      true ->
        Igniter.assign(igniter, :mob_requested, requested -- excluded)
    end
  end

  defp generate_each(%{assigns: %{mob_requested: requested}} = igniter) do
    Enum.reduce(requested, igniter, fn component, acc ->
      # --no-register on each: the registry is written once at the end instead.
      Igniter.compose_task(acc, "mishka.ui.gen.mob", [component | flags(igniter)])
    end)
  end

  defp generate_each(igniter), do: igniter

  defp flags(igniter) do
    options = igniter.args.options

    ["--sub", "--yes", "--no-register"]
    |> prepend("--module-prefix", options[:module_prefix])
    |> prepend("--component-prefix", options[:component_prefix])
  end

  defp prepend(flags, _name, value) when value in [nil, ""], do: flags
  defp prepend(flags, name, value), do: [name, value | flags]

  defp write_registry(%{assigns: %{mob_requested: _}} = igniter) do
    options = igniter.args.options

    igniter
    |> Igniter.assign(:module_prefix, options[:module_prefix] || "")
    |> then(fn acc -> if options[:no_register], do: acc, else: Registry.write(acc) end)
    |> Core.maybe_save_prefixes(options)
  end

  defp write_registry(igniter), do: igniter

  defp split(nil), do: []
  defp split(list), do: list |> String.split(",", trim: true) |> Enum.map(&String.trim/1)
end
