defmodule Mix.Tasks.Mishka.Ui.Gen.Mob.Components do
  use Igniter.Mix.Task

  alias MishkaChelekom.Config
  alias MishkaChelekom.Generators.Core
  alias MishkaChelekom.Generators.Mob.{Locations, Registry}

  @example "mix mishka.ui.gen.mob.components drawer,dialog,tabs"
  @shortdoc "Generate multiple (or all) native Mob components at once"
  @moduledoc """
  #{@shortdoc}

  Pass a comma-separated list of Mob component names, or omit it (or pass `all`) to generate
  every component in `priv/mob/`.

  Each one is generated by `mix mishka.ui.gen.mob`, so dependencies and the shared kit are
  resolved exactly as they are for a single component. The composite registry and Mob's
  `~MOB` tag whitelist are both written **once at the end** rather than after each
  component — doing either 72 times would be correct but pointlessly slow, and the
  whitelist recompiles `:mob`.

  That whitelist is what lets you write `<Chip label="Elixir" />` rather than
  `{chip(label: "Elixir")}`; see `mix mishka.ui.gen.mob` for why it is needed.

  ## Example

  ```bash
  #{@example}
  mix mishka.ui.gen.mob.components             # all of them
  mix mishka.ui.gen.mob.components all         # the same thing
  ```

  ## Options

  * `--exclude` - Comma-separated names to skip
  * `--component-prefix` - Prefix for public function names
  * `--module-prefix` - Prefix for module names
  * `--no-save` - Use prefixes without saving them to config
  * `--no-register` - Do not write the composite-tag registry
  * `--no-tags` - Do not add the tags to Mob's `~MOB` whitelist
  * `--yes` - Apply without prompts
  """

  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      example: @example,
      positional: [{:components, optional: true}],
      group: :mishka_chelekom,
      composes: ["mishka.ui.gen.mob"],
      aliases: [e: :exclude],
      schema: [
        exclude: :csv,
        component_prefix: :string,
        module_prefix: :string,
        no_save: :boolean,
        no_register: :boolean,
        no_tags: :boolean
      ]
    }
  end

  def supports_umbrella?(), do: false

  def igniter(igniter) do
    # See mishka.ui.gen.mob — Owl.Spinner needs its supervisor started.
    Application.ensure_all_started(:owl)
    %Igniter.Mix.Task.Args{positional: %{components: components}, options: options} = igniter.args

    print_banner()
    user_config = Config.load_user_config(igniter)

    tty? = IO.ANSI.enabled?()
    if tty?, do: Owl.Spinner.start(id: :my_spinner, labels: [processing: "Please wait..."])

    list = Core.resolve_components(igniter, components, :mob, user_config, options[:exclude])

    # --no-register/--no-tags on each child: the registry and Mob's tag
    # whitelist are both written once at the end. Doing either 72 times would be
    # correct and pointlessly slow — and the whitelist recompiles :mob, so per
    # component it would rebuild the framework once per component.
    child_args =
      ["--sub", "--yes", "--no-register", "--no-tags"]
      |> Core.append_arg("--component-prefix", options[:component_prefix])
      |> Core.append_arg("--module-prefix", options[:module_prefix])

    igniter =
      igniter
      |> Igniter.assign(:mishka_user_config, user_config)
      |> Igniter.assign(:module_prefix, options[:module_prefix] || "")
      |> Registry.check_dependency()
      |> Locations.assign_namespace()
      |> Core.fan_out("mishka.ui.gen.mob", list, child_args)
      |> write_registry(options)
      |> wire_boot(options)
      |> whitelist_tags(options)
      |> Core.maybe_save_prefixes(options)

    if tty? do
      if Map.get(igniter, :issues, []) == [],
        do: Owl.Spinner.stop(id: :my_spinner, resolution: :ok, label: "Done"),
        else: Owl.Spinner.stop(id: :my_spinner, resolution: :error, label: "Error")
    end

    igniter
  end

  defp write_registry(igniter, options) do
    if options[:no_register], do: igniter, else: Registry.write(igniter)
  end

  defp wire_boot(igniter, options) do
    if options[:no_register], do: igniter, else: Registry.wire_boot(igniter)
  end

  defp whitelist_tags(igniter, options) do
    if options[:no_tags], do: igniter, else: Registry.whitelist(igniter)
  end

  defp print_banner, do: Core.banner(IO.ANSI.magenta(), "Mob")
end
