defmodule MishkaMob.Components.MishkaDrawer do
  @moduledoc """
  Native Mob port of Mishka Chelekom's **Drawer** — an edge-anchored panel
  that slides in over a dimmed backdrop. Built as a pure-Elixir
  `Mob.Composite` (a custom `<MishkaDrawer>` tag), so it ships **no native
  Swift/Kotlin** — it expands into Mob's built-in `Box`/`Row`/`Column`
  widgets at render time.

  ## How Mob draws an overlay

  Mob has no z-index, absolute positioning, or modal slot. The single
  stacking primitive is `:box`, which is a SwiftUI `ZStack` / Compose `Box`:
  its children draw on top of each other, last child on top. A drawer is
  therefore a `Box` that holds `[scrim, panel]` and is itself stacked over
  the screen's own content. The backdrop is just a `Box` with a
  semi-transparent ARGB fill (`0xAARRGGBB`, alpha first).

  ## Usage

  Registered once at boot (see `MishkaMob.App.on_start/0`):

      Mob.Composite.register(:mishka_drawer, {#{inspect(__MODULE__)}, :expand})

  In a screen, make the root a `:box` that stacks your content and the
  drawer, and drive `open` from an assign:

      def render(assigns) do
        %{type: :box, props: %{fill_width: true, fill_height: true}, children: [
          my_content(assigns),
          %{type: :mishka_drawer,
            props: %{open: assigns.drawer_open?, side: :right, title: "Menu",
                     on_close: :close_drawer},
            children: [ menu_item("Profile", :profile), ... ]}
        ]}
      end

      def handle_info({:tap, :open_menu},    s), do: {:noreply, Mob.Socket.assign(s, :drawer_open?, true)}
      def handle_info({:tap, :close_drawer}, s), do: {:noreply, Mob.Socket.assign(s, :drawer_open?, false)}
      # REQUIRED catch-all — see "Host requirement" below.
      def handle_info(_msg, s), do: {:noreply, s}

  Open it from any button (`on_tap: {self(), :open_menu}`). `on_close` fires
  when the backdrop **or** the ✕ button is tapped — the composite auto-wires
  the tuple, so you pass a bare atom.

  ## Host requirement — a catch-all `handle_info/2`

  The panel routes stray taps (on its empty areas) to an ignored tag so they
  don't leak through to the backdrop and dismiss the drawer. That message
  reaches the host screen's `handle_info/2`, so **the screen must have a
  catch-all clause** `def handle_info(_msg, s), do: {:noreply, s}` — without
  it an unmatched message raises `FunctionClauseError` and crashes the
  screen. Every screen generated by `mix mob.new` already has this clause; if
  you hand-write a screen, add it.

  ## Props

  | Prop | Values | Default | Meaning |
  |------|--------|---------|---------|
  | `open` | boolean | `false` | Whether the drawer is shown. Lives in the screen (composites are stateless). |
  | `side` | `:left` `:right` `:top` `:bottom` | `:right` | Edge the panel is pinned to. |
  | `size` | `:xs` `:sm` `:md` `:lg` `:xl` | `:lg` | Panel **width** for `:left`/`:right` (240–384 pt/dp). Ignored for `:top`/`:bottom`, which hug their content. |
  | `title` | string | `nil` | Header title (only when `header` is on). |
  | `header` | boolean | `true` | Render the built-in title + ✕ header. Set `false` to supply your own chrome in the body (the backdrop still dismisses). |
  | `scrim` | boolean | `true` | Dim the background and dismiss on backdrop tap. `false` = a non-blocking panel with no backdrop. |
  | `scrim_color` | color token / ARGB int | `0x99000000` | Backdrop fill (60% black by default). Pass e.g. `0x66000000` for lighter, or `0x00000000` for invisible-but-tappable. |
  | `background` | color token / ARGB int | `:surface` | Panel background. |
  | `padding` | spacing token / number | `:space_lg` | Padding inside the panel around your content. |
  | `corner_radius` | radius token / number | none | Rounds the panel corners (e.g. `:radius_lg` for a rounded bottom sheet). |
  | `on_close` | event tag (atom) | — | Sent to `handle_info/2` as `{:tap, tag}` on backdrop / ✕ tap. Provide it for tap-to-dismiss; without it the ✕ is omitted and only the `open` prop can close the drawer (a warning is logged). |

  Children of the tag become the drawer body (below the header). Build any
  interactive children with an explicit `{self(), tag}` on their `on_tap` —
  only the tag's *own* `on_*` props are auto-wired, not its children's.

  ## Custom design without a new composite

  Most bespoke designs need no fork: the body is entirely yours, and the
  chrome is prop-driven. For a fully custom look, suppress the built-in
  header and style the panel via props:

      %{type: :mishka_drawer,
        props: %{open: @open, side: :bottom, header: false,
                 background: :surface_raised, corner_radius: :radius_lg,
                 scrim_color: 0x66000000, padding: :space_xl,
                 on_close: :close_sheet},
        children: [ my_custom_header(assigns), my_rows(assigns) ]}

  Only reach for your own composite when you need to change the overlay/
  positioning/dismiss *mechanics* — the visual layer is all props + children.

  ## Platform status

  **Verified on Android (Samsung A55, One UI / Android 15)** — all four
  sides anchor correctly, side panels fill height, top/bottom sheets are
  content-height, backdrop taps dismiss (hit-test fall-through works on
  Compose) and panel taps are absorbed. Also source-verified against the iOS
  renderer (`MobRootView.swift`).

  The edge-push filler is a `Spacer` carrying `weight: 1`: iOS `Spacer()`
  fills on its own (weight ignored), while Android's `Spacer` is a
  fixed-size box that needs `weight` to flex — without it, right/bottom
  drawers render at the wrong edge on Android. See `flex_spacer/0`.

  Note the overlay sits inside the top safe-area inset (the framework
  doesn't opt nodes out of it), so the panel starts just below the status
  bar rather than under it — standard mobile drawer behaviour.
  """

  require Logger

  # Panel width per size token, for left/right drawers (matches Mishka's
  # w-60..w-96 scale). Top/bottom drawers are content-height instead.
  @sizes %{xs: 240, sm: 256, md: 288, lg: 320, xl: 384}

  # ~60% black backdrop — the native equivalent of Mishka's `bg-black/60`.
  @scrim 0x99_00_00_00

  # A benign event the panel uses to swallow taps: a filled Box with no
  # on_tap gets no hit-test shape natively, so taps in the panel's empty
  # areas would fall through to the scrim and close the drawer. Routing them
  # to a tag the screen ignores (its catch-all `handle_info/2`) absorbs them.
  @absorb_tag :__mishka_drawer_ignore

  @doc """
  Composite expander. `props` arrive with `on_*` targets already resolved to
  `{screen_pid, tag}` tuples; `ctx` is `%{screen: pid}` (only `:screen` — the
  framework moduledoc's `:platform` key does not exist in the code, so don't
  read it). Returns a Mob node map — an empty column when closed, the overlay
  tree when open.
  """
  @spec expand(map(), [map()], %{screen: pid()}) :: map()
  def expand(props, children, ctx) do
    if truthy?(Map.get(props, :open, false)) do
      warn_if_no_dismiss(props)
      overlay(props, children, ctx)
    else
      empty()
    end
  end

  # ── Overlay: scrim (bottom) + edge-anchored panel (top) inside a fill Box ──
  defp overlay(props, children, ctx) do
    side = Map.get(props, :side, :right)
    close = Map.get(props, :on_close)
    positioner = positioner(side, panel(props, children, ctx))

    scrim =
      if Map.get(props, :scrim, true) do
        scrim_bg = Map.get(props, :scrim_color, @scrim)

        maybe_tap(
          %{
            type: :box,
            props: %{fill_width: true, fill_height: true, background: scrim_bg},
            children: []
          },
          close
        )
      end

    %{
      type: :box,
      props: %{fill_width: true, fill_height: true},
      children: Enum.reject([scrim, positioner], &is_nil/1)
    }
  end

  # Push the panel to its edge with a flex Spacer. Left/right split a Row;
  # top/bottom split a fill-height Column. The positioner sits on top of the
  # scrim; its Spacer half has no fill/handler, so taps there fall through to
  # the scrim (dismiss). The panel half absorbs its own taps.
  defp positioner(:left, panel), do: row([panel, flex_spacer()])
  defp positioner(:right, panel), do: row([flex_spacer(), panel])
  defp positioner(:top, panel), do: fill_column([panel, flex_spacer()])
  defp positioner(:bottom, panel), do: fill_column([flex_spacer(), panel])

  # ── The panel: a Box (background / corner_radius / tap-absorb) wrapping an
  # inner Column that holds the padding + content. Left/right are width-locked
  # and full-height (the inner column's fill_height is what stretches the
  # width-locked box); top/bottom fill width and hug their content height.
  # `children` are the tag's RAW children (Mob.Composite passes them
  # un-expanded and re-expands this output to a fixpoint, so nested composites
  # still resolve) — splicing them in directly is correct.
  defp panel(props, children, ctx) do
    side = Map.get(props, :side, :right)
    padding = Map.get(props, :padding, :space_lg)
    bg = Map.get(props, :background, :surface)
    absorb = {ctx.screen, @absorb_tag}
    corner_radius = Map.get(props, :corner_radius)

    if side in [:left, :right] do
      # Fixed width + full height: a width-locked Box (which clips corner_radius
      # on both platforms) wrapping a fill_height Column that carries the padding
      # and stretches the box to full height.
      box_props =
        %{width: size_px(props), background: bg, on_tap: absorb}
        |> maybe_put(:corner_radius, corner_radius)

      inner = %{
        type: :column,
        props: %{fill_width: true, fill_height: true, padding: padding},
        children: body(props, children)
      }

      %{type: :box, props: box_props, children: [inner]}
    else
      # Full width, content height: a Column fills width on BOTH platforms
      # (a Box wraps its content on Compose, collapsing the sheet). corner_radius
      # clips on Android's Column; iOS VStack doesn't round — acceptable.
      col_props =
        %{fill_width: true, background: bg, padding: padding, on_tap: absorb}
        |> maybe_put(:corner_radius, corner_radius)

      %{type: :column, props: col_props, children: body(props, children)}
    end
  end

  # Header (title + ✕) above the caller's children, unless `header: false`.
  defp body(props, children) do
    header =
      Map.get(props, :header, true) &&
        header(Map.get(props, :title), Map.get(props, :on_close))

    if header, do: [header, gap(16) | children], else: children
  end

  # Header row: optional title on the leading side; a ✕ close button on the
  # trailing side ONLY when on_close is set (a ✕ with no handler would be a
  # dead control). Returns nil when there is nothing to show.
  defp header(title, close) do
    lead = if is_binary(title) and title != "", do: [title_text(title)], else: []
    trail = if tap?(close), do: [flex_spacer(), close_button(close)], else: []

    case lead ++ trail do
      [] -> nil
      children -> %{type: :row, props: %{fill_width: true}, children: children}
    end
  end

  defp title_text(title),
    do: %{
      type: :text,
      props: %{text: title, text_size: :xl, text_color: :on_surface},
      children: []
    }

  defp close_button(close) do
    %{
      type: :button,
      props: %{
        text: "✕",
        background: :transparent,
        text_color: :on_surface,
        text_size: :xl,
        padding: :space_xs,
        fill_width: false,
        on_tap: close
      },
      children: []
    }
  end

  defp warn_if_no_dismiss(props) do
    unless tap?(Map.get(props, :on_close)) do
      Logger.warning(
        "[MishkaDrawer] open with no `on_close` — the backdrop and ✕ cannot dismiss it; " <>
          "it can only be closed by flipping the `open` prop from the screen."
      )
    end
  end

  # ── Small node helpers ──
  defp row(children), do: %{type: :row, props: %{fill_width: true}, children: children}

  defp fill_column(children),
    do: %{type: :column, props: %{fill_width: true, fill_height: true}, children: children}

  # A flex filler that pushes the panel to the far edge. It must fill remaining
  # space on BOTH platforms, and the mechanism differs: iOS `Spacer()` (size-less)
  # already fills but ignores `weight`; Android's Spacer is a FIXED-size box
  # (size-less = zero) and needs `weight` to flex. Carrying both makes one filler
  # work everywhere. Without this, right/bottom drawers render at the wrong edge
  # on Android (the panel collapses to the start).
  defp flex_spacer, do: %{type: :spacer, props: %{weight: 1}, children: []}
  defp gap(size), do: %{type: :spacer, props: %{size: size}, children: []}
  defp empty, do: %{type: :column, props: %{}, children: []}

  defp size_px(props), do: Map.get(@sizes, Map.get(props, :size, :lg), 320)

  # Attach an event tuple only when the caller actually supplied one.
  defp maybe_tap(node, {pid, _tag} = tap) when is_pid(pid),
    do: %{node | props: Map.put(node.props, :on_tap, tap)}

  defp maybe_tap(node, _), do: node

  defp maybe_put(map, _key, nil), do: map
  defp maybe_put(map, key, value), do: Map.put(map, key, value)

  defp tap?({pid, _tag}) when is_pid(pid), do: true
  defp tap?(_), do: false

  defp truthy?(nil), do: false
  defp truthy?(false), do: false
  defp truthy?(_), do: true
end
