defmodule MishkaChelekomWeb.Components.MishkaComponents do
  defmacro __using__(_) do
    quote do
      import MishkaChelekomWeb.Components.{
               Accordion,
               Alert,
               Avatar,
               Badge,
               Banner,
               Blockquote,
               Breadcrumb,
               Button,
               Card,
               Carousel,
               Chat,
               ChekboxField,
               ColorField,
               DateTimeField,
               DeviceMockup,
               Divider,
               Drawer,
               Dropdown,
               EmailField,
               Fieldset,
               FileField,
               Footer,
               FormWrapper,
               Gallery,
               Image,
               Indicator,
               InputField,
               Jumbotron,
               Keyboard,
               List,
               MegaMenu,
               Menu,
               Modal,
               NativeSelect,
               Navbar,
               NumberField,
               Overlay,
               Pagination,
               PasswordField,
               Popover,
               Progress,
               RadioField,
               RangeField,
               Rating,
               SearchField,
               Sidebar,
               Skeleton,
               SpeedDial,
               Spinner,
               Stepper,
               Table,
               TableContent,
               Tabs,
               TelField,
               TextField,
               TextareaField,
               Timeline,
               Toast,
               ToggleField,
               Tooltip,
               Typography,
               UrlField,
               Video
             },
             only: [
               accordion: 1,
               native_accordion: 1,
               flash: 1,
               flash_group: 1,
               alert: 1,
               avatar: 1,
               avatar_group: 1,
               badge: 1,
               banner: 1,
               blockquote: 1,
               breadcrumb: 1,
               button_group: 1,
               button: 1,
               input_button: 1,
               button_link: 1,
               card: 1,
               card_title: 1,
               card_media: 1,
               card_content: 1,
               card_footer: 1,
               carousel: 1,
               chat: 1,
               chat_section: 1,
               checkbox: 1,
               group_checkbox: 1,
               color_field: 1,
               date_time_field: 1,
               device_mockup: 1,
               divider: 1,
               hr: 1,
               drawer: 1,
               dropdown: 1,
               dropdown_trigger: 1,
               dropdown_content: 1,
               email_field: 1,
               fieldset: 1,
               file_field: 1,
               footer: 1,
               footer_section: 1,
               form_wrapper: 1,
               gallery: 1,
               gallery_media: 1,
               image: 1,
               indicator: 1,
               input_field: 1,
               jumbotron: 1,
               keyboard: 1,
               list: 1,
               li: 1,
               ul: 1,
               ol: 1,
               list_group: 1,
               mega_menu: 1,
               menu: 1,
               modal: 1,
               native_select: 1,
               select_option_group: 1,
               navbar: 1,
               number_field: 1,
               overlay: 1,
               pagination: 1,
               password_field: 1,
               popover: 1,
               popover_trigger: 1,
               popover_content: 1,
               progress: 1,
               progress_section: 1,
               radio_field: 1,
               range_field: 1,
               rating: 1,
               search_field: 1,
               sidebar: 1,
               skeleton: 1,
               speed_dial: 1,
               spinner: 1,
               stepper: 1,
               stepper_section: 1,
               table: 1,
               th: 1,
               tr: 1,
               td: 1,
               table_content: 1,
               content_wrapper: 1,
               content_item: 1,
               tabs: 1,
               tel_field: 1,
               text_field: 1,
               textarea_field: 1,
               timeline: 1,
               timeline_section: 1,
               toast: 1,
               toast_group: 1,
               toggle_field: 1,
               tooltip: 1,
               h1: 1,
               h2: 1,
               h3: 1,
               h4: 1,
               h5: 1,
               h6: 1,
               p: 1,
               strong: 1,
               em: 1,
               dl: 1,
               dt: 1,
               dd: 1,
               figure: 1,
               figcaption: 1,
               abbr: 1,
               mark: 1,
               small: 1,
               s: 1,
               u: 1,
               cite: 1,
               del: 1,
               url_field: 1,
               video: 1
             ]
    end
  end
end
