name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ["1.18.4"]
        otp: ["28"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.20.4
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Create formatter for tests
        run: |
          echo '[inputs: ["*.{ex,exs}", "{config,lib,test}/**/*.{ex,exs}"]]' > /tmp/.formatter.exs

      - name: Run tests
        env:
          MIX_ENV: test
        run: mix test --trace
