defmodule MishkaChelekom.Generators.Mob.Registry do
  @moduledoc """
  Maintains `lib/<app>/components.ex` — the module that registers every generated
  component as a `Mob.Composite` tag.

  Without registration a component still works when called as a function, but
  `<MishkaDrawer>` in `~MOB` markup does not resolve. Registering is one line per
  component, and forgetting it produces markup that renders nothing with no error.

  ## Rebuilt, not appended

  The registry is regenerated from the component files actually present, rather
  than having a line appended on each run. Appending is what makes generators
  produce duplicate entries when re-run and stale ones after an uninstall; a
  rebuild is idempotent by construction.
  """

  alias Igniter.Project.Application, as: IAPP
  alias MishkaChelekom.Generators.Core
  alias MishkaChelekom.Generators.Mob.Locations

  @doc """
  Write the registry for whatever components exist, on disk or pending in this
  Igniter run.
  """
  @spec write(Igniter.t()) :: Igniter.t()
  def write(igniter) do
    case entries(igniter) do
      [] ->
        igniter

      entries ->
        path = Locations.registry_path(igniter)

        igniter
        |> Core.track_generated_file(path)
        |> Igniter.create_new_file(path, contents(igniter, entries), on_exists: :overwrite)
    end
  end

  @doc """
  Every `{tag, module}` pairing the registry should contain, sorted.

  Considers both files already on disk and files created earlier in this same
  run — a single `mix mishka.ui.gen.mob dialog` that pulls in siblings has to
  register all of them, and none of those exist on disk yet.
  """
  @spec entries(Igniter.t()) :: [{atom(), module()}]
  def entries(igniter) do
    dir = Locations.components_dir(igniter)
    known = MapSet.new(Core.all_component_names(igniter, :mob))
    prefix = Map.get(igniter.assigns, :module_prefix, "")

    (Path.wildcard("#{dir}/*.ex") ++ pending(igniter, dir))
    |> Enum.map(&Path.basename(&1, ".ex"))
    |> Enum.uniq()
    |> Enum.map(&{&1, String.replace_prefix(&1, prefix, "")})
    |> Enum.filter(fn {_file, component} -> MapSet.member?(known, component) end)
    |> Enum.map(fn {file, component} ->
      {String.to_atom("mishka_#{component}"),
       Core.module_atom("#{igniter.assigns.mob_namespace}.#{file}")}
    end)
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp pending(igniter, dir) do
    igniter.rewrite.sources
    |> Map.keys()
    |> Enum.filter(&String.starts_with?(&1, dir <> "/"))
  end

  defp contents(igniter, entries) do
    module = igniter.assigns.mob_namespace
    base = Locations.base_module(igniter)

    pairs =
      Enum.map_join(entries, ",\n", fn {tag, component} ->
        "    {#{inspect(tag)}, #{component}}"
      end)

    example_tag =
      entries |> List.first() |> elem(0) |> Atom.to_string() |> Macro.camelize()

    """
    defmodule #{module} do
      @moduledoc \"\"\"
      Composite-tag registry for the generated Mob components.

      Call `register_all/0` once at boot, from your app's `on_start/0`:

          def on_start do
            #{module}.register_all()
            Mob.Nav.push(#{base}.HomeScreen)
          end

      After that, `<#{example_tag} />` resolves as a tag in `~MOB` markup.

      Regenerated by `mix mishka.ui.gen.mob` — edits are overwritten. Pass
      `--no-register` if you would rather own this file yourself.
      \"\"\"

      @composites [
    #{pairs}
      ]

      @doc "Every `{tag, module}` pairing this app registers."
      @spec composites() :: [{atom(), module()}]
      def composites, do: @composites

      @doc "Registers every composite tag with `Mob.Composite`."
      @spec register_all() :: :ok
      def register_all do
        Enum.each(@composites, fn {tag, module} ->
          Mob.Composite.register(tag, {module, :expand})
        end)
      end
    end
    """
  end

  @doc """
  Adds an issue unless the project depends on `:mob`.

  `Core.check_dependencies/1` requires Phoenix, which a Mob application does not
  have — it is a plain OTP app that renders native widgets.
  """
  @spec check_dependency(Igniter.t()) :: Igniter.t()
  def check_dependency(igniter) do
    case Igniter.Project.Deps.get_dep(igniter, :mob) do
      {:ok, nil} ->
        Igniter.add_warning(igniter, """
        This project does not depend on :mob.

        Mob components render native widgets through the Mob runtime. Add it with:

            {:mob, "~> 0.7"}

        The files will still be generated — they just will not compile until the
        dependency is there.
        """)

      _ ->
        igniter
    end
  end

  @doc false
  @spec app_name(Igniter.t()) :: atom()
  def app_name(igniter), do: IAPP.app_name(igniter)
end
